#!/usr/bin/env python3
"""
One-off generator for the targeted German B1 exam prep Anki deck.

Reads:  flashcards/exam_prep/exam_items.yaml
Output: flashcards/exam_prep/german_b1_prufung.apkg

Card types per item:
  - ExamReverse note → 2 cards (DE→RU and RU→DE)
  - ExamCloze note   → 1 card  (fill-in-the-blank)

Content generated by Claude, validated by Gemini.
All card content in German and Russian only — no English.

Usage:
    python3 flashcards/scripts/generate_exam_deck.py
    python3 flashcards/scripts/generate_exam_deck.py --dry-run
    python3 flashcards/scripts/generate_exam_deck.py --items konjunktiv_II
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import genanki
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

_NOHOOKS_DIR = Path.home() / ".config" / "nohooks"

EXAM_PREP_DIR = PROJECT_ROOT / "flashcards" / "exam_prep"
ITEMS_FILE = EXAM_PREP_DIR / "exam_items.yaml"
OUTPUT_FILE = EXAM_PREP_DIR / "german_b1_prufung.apkg"
GENERATED_JSON = EXAM_PREP_DIR / "generated_cards.json"

DECK_NAME = "Deutsch B1::Prüfung"
DECK_ID = 1586166099  # fixed for consistency

# Anki model IDs — fixed so re-imports update existing notes
MODEL_ID_REVERSE = 1586166100
MODEL_ID_CLOZE = 1586166101

GENERATION_MODEL = "claude-sonnet-4-6"

try:
    import anthropic

    HAS_SDK = bool(os.environ.get("ANTHROPIC_API_KEY"))
except ImportError:
    HAS_SDK = False


# ─── CSS ──────────────────────────────────────────────────────────────────────

CSS = """
.card {
    font-family: Arial, sans-serif;
    font-size: 18px;
    text-align: center;
    color: #333;
    background-color: #fafafa;
    padding: 24px;
    max-width: 620px;
    margin: 0 auto;
}
.term {
    font-size: 36px;
    font-weight: bold;
    color: #1a3a5c;
    margin-bottom: 8px;
}
.russian {
    font-size: 30px;
    font-weight: bold;
    color: #2c3e50;
    margin-bottom: 10px;
}
.category-badge {
    display: inline-block;
    background: #e8f0fe;
    color: #1a3a5c;
    border-radius: 12px;
    padding: 3px 12px;
    font-size: 13px;
    margin-bottom: 14px;
}
.hint {
    font-size: 15px;
    color: #7f8c8d;
    font-style: italic;
    margin-bottom: 14px;
}
hr { border: none; border-top: 1px solid #ddd; margin: 18px 0; }
.example {
    text-align: left;
    background: #fff;
    border-left: 4px solid #3b82f6;
    padding: 10px 14px;
    border-radius: 6px;
    margin: 12px 0;
}
.example-de {
    font-size: 17px;
    color: #1a3a5c;
    font-style: italic;
    margin-bottom: 5px;
}
.example-de strong { color: #3b82f6; font-weight: bold; }
.example-ru { font-size: 15px; color: #7f8c8d; }
.notes {
    font-size: 14px;
    color: #888;
    font-style: italic;
    text-align: left;
    margin-top: 12px;
    padding: 8px 12px;
    background: #f5f5f5;
    border-radius: 4px;
}
.cloze { font-weight: bold; color: #1a3a5c; }
"""


# ─── Anki models ──────────────────────────────────────────────────────────────


def make_reverse_model() -> genanki.Model:
    return genanki.Model(
        MODEL_ID_REVERSE,
        "Exam B1 Reverse",
        fields=[
            {"name": "Term"},
            {"name": "Russian"},
            {"name": "Category"},
            {"name": "DisambiguationHint"},
            {"name": "ExampleDE"},
            {"name": "ExampleRU"},
            {"name": "NotesRU"},
        ],
        templates=[
            {
                "name": "DE→RU",
                "qfmt": (
                    '<div class="term">{{Term}}</div><div class="category-badge">{{Category}}</div>'
                ),
                "afmt": (
                    '<div class="term">{{Term}}</div>'
                    "<hr>"
                    '<div class="russian">{{Russian}}</div>'
                    '{{#ExampleDE}}<div class="example">'
                    '<div class="example-de">{{ExampleDE}}</div>'
                    '<div class="example-ru">{{ExampleRU}}</div>'
                    "</div>{{/ExampleDE}}"
                    '{{#NotesRU}}<div class="notes">{{NotesRU}}</div>{{/NotesRU}}'
                ),
            },
            {
                "name": "RU→DE",
                "qfmt": (
                    '<div class="russian">{{Russian}}</div>'
                    '<div class="category-badge">{{Category}}</div>'
                    "{{#DisambiguationHint}}"
                    '<div class="hint">{{DisambiguationHint}}</div>'
                    "{{/DisambiguationHint}}"
                ),
                "afmt": (
                    '<div class="russian">{{Russian}}</div>'
                    "<hr>"
                    '<div class="term">{{Term}}</div>'
                    '{{#ExampleDE}}<div class="example">'
                    '<div class="example-de">{{ExampleDE}}</div>'
                    '<div class="example-ru">{{ExampleRU}}</div>'
                    "</div>{{/ExampleDE}}"
                    '{{#NotesRU}}<div class="notes">{{NotesRU}}</div>{{/NotesRU}}'
                ),
            },
        ],
        css=CSS,
    )


def make_cloze_model() -> genanki.Model:
    return genanki.Model(
        MODEL_ID_CLOZE,
        "Exam B1 Cloze",
        model_type=genanki.Model.CLOZE,
        fields=[
            {"name": "Text"},
            {"name": "Extra"},
        ],
        templates=[
            {
                "name": "Cloze",
                "qfmt": "{{cloze:Text}}",
                "afmt": "{{cloze:Text}}<hr>{{Extra}}",
            }
        ],
        css=CSS,
    )


# ─── LLM generation ───────────────────────────────────────────────────────────


def run(cmd: list[str], cwd: Path | None = None, unset_claudecode: bool = False) -> str:
    env = None
    if unset_claudecode:
        env = {k: v for k, v in os.environ.items() if k != "CLAUDECODE"}
    result = subprocess.run(
        cmd, capture_output=True, text=True, check=True, cwd=cwd or _NOHOOKS_DIR, env=env
    )
    return result.stdout


def _strip_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text
        text = text.rsplit("```", 1)[0].strip()
    return text


def generate_content(item: dict) -> dict:
    """Call Claude to generate Russian translation, examples, cloze, notes."""
    prompt = f"""Создай контент для карточки Anki (немецкий-русский, уровень B1).

Слово/фраза: {item["term"]}
Категория: {item["category"]}
Часть речи: {item["pos"]}
Подсказка для разграничения: {item["disambiguation_hint"]}

Верни ТОЛЬКО JSON без комментариев и markdown:
{{
  "russian": "точный краткий перевод на русский (без скобок если можно)",
  "example_de": "одно натуральное немецкое предложение (8-14 слов), где видно использование слова/фразы",
  "example_ru": "точный перевод примера на русский",
  "cloze_de": "то же предложение, где ключевое слово/фраза заменена на {{{{c1::СЛОВО}}}}",
  "notes_ru": "2-3 предложения на русском: как отличить от похожих форм, управление падежом, порядок слов. Если есть синонимы — 'Также принимается: X, Y'"
}}

Требования:
- Только немецкий и русский — НИКАКОГО английского нигде
- В cloze должен быть ровно ОДИН правильный ответ (не синоним)
- Для составных фраз (deshalb / darum / deswegen) cloze выбери ОДНО слово из группы
- Пример должен чётко демонстрировать использование, а не быть абстрактным
"""

    if HAS_SDK:
        client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        msg = client.messages.create(
            model=GENERATION_MODEL,
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = msg.content[0].text  # type: ignore[union-attr]
    else:
        raw = run(["claude", "-p", prompt, "--model", GENERATION_MODEL], unset_claudecode=True)

    return json.loads(_strip_fences(raw))


def validate_content(term: str, content: dict) -> tuple[bool, str]:
    """Use Gemini to validate the generated card content."""
    prompt = f"""Проверь контент карточки Anki (немецкий-русский, уровень B1).

Слово/фраза: {term}
Контент:
{json.dumps(content, ensure_ascii=False, indent=2)}

Проверь:
1. Перевод на русский точный и адекватный
2. Немецкий пример грамматически правильный и естественный
3. Перевод примера точен
4. В cloze ровно один правильный ответ (не подходит синоним)
5. Нет английского нигде

Ответ ТОЛЬКО JSON:
{{"valid": true, "issues": []}}
или
{{"valid": false, "issues": ["проблема 1", "проблема 2"]}}"""

    try:
        raw = run(["gemini", "-p", prompt], unset_claudecode=True)
        data = json.loads(_strip_fences(raw))
        return data.get("valid", False), "; ".join(data.get("issues", []))
    except Exception as e:
        print(f"  ⚠️  Gemini validation failed: {e} — accepting as-is")
        return True, ""


# ─── Card building ─────────────────────────────────────────────────────────────


def build_notes(
    item: dict,
    content: dict,
    reverse_model: genanki.Model,
    cloze_model: genanki.Model,
) -> tuple[genanki.Note, genanki.Note]:
    """Build one ExamReverse note and one ExamCloze note from item + content."""

    # Highlight the key term in example_de
    example_de_display = content.get("example_de", "")
    # Bold the term if it appears
    for t in item["term"].split(" / "):
        t_clean = t.strip().removesuffix("(+Akk)").removesuffix("(+Dat)").strip()
        if t_clean and t_clean.lower() in example_de_display.lower():
            example_de_display = example_de_display.replace(
                t_clean, f"<strong>{t_clean}</strong>", 1
            )
            break

    category_display = item["category"].replace("_", " ")

    reverse_note = genanki.Note(
        model=reverse_model,
        fields=[
            item["term"],
            content.get("russian", ""),
            category_display,
            item.get("disambiguation_hint", ""),
            example_de_display,
            content.get("example_ru", ""),
            content.get("notes_ru", ""),
        ],
        guid=genanki.guid_for(f"exam_reverse_{item['id']}"),
    )

    cloze_note = genanki.Note(
        model=cloze_model,
        fields=[
            content.get("cloze_de", ""),
            f"{content.get('russian', '')} | {content.get('notes_ru', '')}",
        ],
        guid=genanki.guid_for(f"exam_cloze_{item['id']}"),
    )

    return reverse_note, cloze_note


# ─── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate German B1 exam prep Anki deck",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                         # generate all items
  %(prog)s --dry-run               # show items without calling LLM
  %(prog)s --items Konjunktiv_II   # only items of this category
  %(prog)s --skip-validation       # generate without Gemini check
        """,
    )
    parser.add_argument("--dry-run", action="store_true", help="List items without calling LLM")
    parser.add_argument("--items", help="Only generate items of this category")
    parser.add_argument("--skip-validation", action="store_true", help="Skip Gemini validation")
    args = parser.parse_args()

    with open(ITEMS_FILE, encoding="utf-8") as f:
        all_items = yaml.safe_load(f)["items"]

    items = all_items
    if args.items:
        items = [i for i in items if i["category"].lower() == args.items.lower()]
        if not items:
            print(f"No items found for category: {args.items}")
            sys.exit(1)

    print("\n📚 German B1 Exam Prep Deck Generator")
    print(f"   Items: {len(items)} | Output: {OUTPUT_FILE.name}")
    print(f"   Deck: {DECK_NAME}")
    print("=" * 60)

    if args.dry_run:
        for item in items:
            print(f"  [{item['category']:16}] {item['term']}")
        print(f"\nTotal: {len(items)} items → ~{len(items) * 3} cards (2 reverse + 1 cloze each)")
        return

    if not HAS_SDK and not __import__("shutil").which("claude"):
        print("ERROR: Need ANTHROPIC_API_KEY or 'claude' CLI.")
        sys.exit(1)
    if not args.skip_validation and not __import__("shutil").which("gemini"):
        print("ERROR: 'gemini' CLI not found. Use --skip-validation to skip.")
        sys.exit(1)

    reverse_model = make_reverse_model()
    cloze_model = make_cloze_model()
    deck = genanki.Deck(DECK_ID, DECK_NAME)

    generated: list[dict] = []
    failed: list[str] = []

    for item in items:
        print(f"\n🔤  {item['term']}  [{item['category']}]")

        # Generate (up to 3 attempts)
        content = None
        for attempt in range(1, 4):
            try:
                content = generate_content(item)
                print(f"   ✅ Generated: {content.get('russian', '')[:50]}")
                break
            except Exception as e:
                if attempt < 3:
                    print(f"   ⚠️  Attempt {attempt} failed ({e}) — retrying...")
                else:
                    print(f"   ❌ Generation failed after 3 attempts: {e}")
                    failed.append(item["id"])
        if content is None:
            continue

        # Validate
        if not args.skip_validation:
            valid, issues = validate_content(item["term"], content)
            if not valid:
                print(f"   ⚠️  Validation issues: {issues} — retrying...")
                try:
                    retry_prompt_addition = f"\nПредыдущая попытка имела проблемы: {issues}"
                    item_copy = dict(item)
                    item_copy["disambiguation_hint"] += retry_prompt_addition
                    content = generate_content(item_copy)
                    valid, issues = validate_content(item["term"], content)
                    if valid:
                        print("   ✅ Retry succeeded")
                    else:
                        print(f"   ❌ Retry also failed: {issues} — using anyway")
                except Exception as e:
                    print(f"   ❌ Retry failed: {e}")
        else:
            print("   ⏭️  Validation skipped")

        # Build notes
        reverse_note, cloze_note = build_notes(item, content, reverse_model, cloze_model)
        deck.add_note(reverse_note)
        deck.add_note(cloze_note)

        generated.append({"item": item, "content": content})

    # Save generated JSON for inspection
    EXAM_PREP_DIR.mkdir(parents=True, exist_ok=True)
    with open(GENERATED_JSON, "w", encoding="utf-8") as f:
        json.dump(generated, f, ensure_ascii=False, indent=2)
    print(f"\n📄 Generated data saved → {GENERATED_JSON.name}")

    # Write deck
    package = genanki.Package(deck)
    package.write_to_file(str(OUTPUT_FILE))

    print("\n" + "=" * 60)
    print(f"✅ Deck written: {OUTPUT_FILE}")
    print(f"   {len(generated)} items → ~{len(generated) * 3} cards")
    if failed:
        print(f"   ❌ Failed: {', '.join(failed)}")
    print("\n\U0001f4a1 Subdeck tip: In Anki, drag your vocabulary deck under 'Deutsch B1'")
    print("   to share a daily new-card limit with this deck.")


if __name__ == "__main__":
    main()
